[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/rest/bodies/:name"
  to = "/.netlify/functions/solar-body?name=:name"
  status = 200
  force = true
